root_domain: mc.example.net
mc_listen_host: 0.0.0.0
mc_listen_port: 25565
api_listen_host: 0.0.0.0
api_listen_port: 8000
root_domain_motd: "Welcome to Minegate"
root_domain_icon: null
not_found_motd: "Server does not exist"
not_found_icon: null
server_offline_motd: "Server %s is offline!"
server_offline_icon: null
routes:
  - subdomain: survival
    backends:
      - host: 192.168.1.100
        port: 25565
        weight: 1
        priority: 0
      - host: 192.168.1.101
        port: 25565
        weight: 2
        priority: 0
    load_balance:
      strategy: least_connections
  - subdomain: creative
    backends:
      - host: 192.168.1.200
        port: 25565
    load_balance:
      strategy: round_robin
